# Generated by Django 5.2.7 on 2025-10-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField()),
                ('text_alt', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Privacypolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.CharField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
