# Generated by Django 5.2.7 on 2025-10-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='text_alt',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='../static/images/'),
        ),
    ]
