# Generated by Django 5.2.7 on 2025-10-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imagegallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='Название сайта')),
                ('salon_address', models.TextField(verbose_name='Адрес салона')),
                ('salon_phone', models.CharField(max_length=20, verbose_name='Телефон салона')),
                ('salon_email', models.EmailField(max_length=254, verbose_name='Email салона')),
                ('telegram_bot_token', models.CharField(max_length=100, verbose_name='API токен Telegram-бота')),
                ('telegram_chat_id', models.CharField(max_length=50, verbose_name='ID чата Telegram')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='privacy_policy',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
