# Generated by Django 5.2.7 on 2025-10-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_settings_alter_privacypolicy_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Надпись при наведении на текст или при незагрузке изображения', max_length=200),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='updated_at',
            field=models.DateField(auto_now=True, help_text='Не трогать'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='telegram_bot_token',
            field=models.CharField(help_text='Подробности - в инструкции', max_length=100, verbose_name='API токен Telegram-бота'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='telegram_chat_id',
            field=models.CharField(help_text='Подробности - в инструкции', max_length=50, verbose_name='ID чата Telegram'),
        ),
    ]
