# Generated by Django 5.2.7 on 2025-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_callbackrequest_alter_imagegallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='salon_tgk',
            field=models.CharField(blank=True, verbose_name='Ссылка на Telegram канал'),
        ),
        migrations.AddField(
            model_name='settings',
            name='ymap_widget',
            field=models.CharField(blank=True, verbose_name='Ссылка на виджет YMaps'),
        ),
    ]
