# Generated by Django 5.2.7 on 2025-10-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_settings_salon_tgk_settings_ymap_widget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='telegram_bot_token',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='telegram_chat_id',
        ),
    ]
