# Generated by Django 5.2.7 on 2025-10-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=255)),
                ('work_description', models.CharField(max_length=255)),
                ('vehicle_make', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('work_type', models.CharField(max_length=255)),
                ('before_after', models.BooleanField(default=False)),
                ('work_image', models.ImageField(upload_to='../static/images/')),
                ('work_image_two', models.ImageField(default=None, upload_to='../static/images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('alt_text_two', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
