# Generated by Django 5.2.7 on 2025-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='work_image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='work_image_two',
            field=models.ImageField(default=None, upload_to='gallery/'),
        ),
    ]
