# Generated by Django 5.2.7 on 2025-10-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_galleryimage_work_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_text_two',
            field=models.CharField(blank=True, help_text='Только если стоит галочка на before/after', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='work_image_two',
            field=models.ImageField(blank=True, default=None, help_text='Только если стоит галочка на before/after', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='work_type',
            field=models.CharField(help_text="Только: exterior/interior, если не указывать - то будет показано как 'Индивидуальное решение'", max_length=255),
        ),
    ]
