# Generated by Django 5.2.7 on 2025-10-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_galleryimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Работа портфолио', 'verbose_name_plural': 'Работы портфолио'},
        ),
    ]
