# Generated by Django 5.2.7 on 2025-10-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Используется в URL', unique=True, verbose_name='Слаг')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('content', models.TextField(help_text='Поддерживается HTML', verbose_name='Полный текст статьи')),
                ('reading_time_minutes', models.PositiveSmallIntegerField(verbose_name='Время чтения (минуты)')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL изображения (превью)')),
                ('hero_image_url', models.URLField(blank=True, max_length=500, verbose_name='URL изображения (детальная)')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at'],
            },
        ),
    ]
