# Generated by Django 5.2.7 on 2025-10-22 20:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название опции')),
                ('price_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фиксированная цена')),
                ('price_percent', models.FloatField(blank=True, help_text='Например: 10% = 0.1', null=True, verbose_name='Процент от стоимости детали')),
                ('applies_to_body_part', models.BooleanField(default=True, verbose_name='Применяется к выбранным деталям')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Дополнительная опция',
                'verbose_name_plural': 'Дополнительные опции',
            },
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название детали')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена (для легкового)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Деталь кузова',
                'verbose_name_plural': 'Детали кузова',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Максимальная сумма (оставьте пустым для 'и выше')")),
                ('discount_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], verbose_name='Скидка (%)')),
            ],
            options={
                'verbose_name': 'Порог скидки',
                'verbose_name_plural': 'Пороги скидок',
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='FilmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название пленки')),
                ('price_multiplier', models.FloatField(default=1.0, verbose_name='Множитель цены')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип пленки',
                'verbose_name_plural': 'Типы пленок',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('base_multiplier', models.FloatField(default=1.0, verbose_name='Базовый коэффициент сложности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип автомобиля',
                'verbose_name_plural': 'Типы автомобилей',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая цена')),
                ('discount_applied', models.FloatField(default=0, verbose_name='Скидка (%)')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('film_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.filmtype', verbose_name='Тип пленки')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.vehicletype', verbose_name='Тип авто')),
            ],
            options={
                'verbose_name': 'Заявка на оклейку',
                'verbose_name_plural': 'Заявки на оклейку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelectedBodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.bodypart')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_parts', to='calculator.bookingrequest')),
            ],
            options={
                'verbose_name': 'Выбранная деталь',
                'verbose_name_plural': 'Выбранные детали',
            },
        ),
        migrations.CreateModel(
            name='SelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='calculator.bookingrequest')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.additionaloption')),
            ],
            options={
                'verbose_name': 'Выбранная опция',
                'verbose_name_plural': 'Выбранные опции',
            },
        ),
        migrations.AddField(
            model_name='bodypart',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, to='calculator.vehicletype', verbose_name='Поддерживаемые типы авто'),
        ),
    ]
