# Generated by Django 5.2.7 on 2025-10-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_bookingrequest_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='appointment_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Желаемое время записи'),
        ),
    ]
