# Generated by Django 5.2.7 on 2025-10-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_bookingrequest_appointment_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название зоны')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Зона кузова',
                'verbose_name_plural': 'Зоны кузова',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='bodypart',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена'),
        ),
        migrations.AddField(
            model_name='bodypart',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='calculator.bodyzone', verbose_name='Зона кузова'),
        ),
    ]
